
# 数据集相关配置
data:
  dataset: "RainSynAll100"
  image_size: 128
  channels: 3
  num_workers: 8
  data_dir: "/data/sj/tic_4_23_head/TIC"
  conditional: True
  # 2 分类：只区分 head-tic 和 None
  labels: ['None', 'head-tic']

  training:
    batch_size: 16
    patch_n: 16
    n_epochs: 50
    snapshot_freq: 10
    validation_freq: 10000

  sampling:
    batch_size: 2
    last_only: True

# 模型相关配置
model:
  model_name: "/data/sj/videomae_hf/videomae-base-finetuned-kinetics"
  num_classes: 2  # 2 分类
  
  # LoRA 配置
  use_lora: true
  lora_config:
    r: 16
    lora_alpha: 32
    lora_dropout: 0.1
    target_modules: ["query", "value"]
  
  in_channels: 3
  out_ch: 3
  ch: 128
  ch_mult: [1, 2, 3, 4]
  num_res_blocks: 2
  attn_resolutions: [32,]
  dropout: 0.0
  ema_rate: 0.999
  ema: True
  resamp_with_conv: True

# VQModel 配置 (保留)
VQmodel:
  double_z: False
  z_channels: 3
  resolution: 256
  in_channels: 3
  out_ch: 3
  ch: 128
  ch_mult: [ 1,2,4 ] 
  num_res_blocks: 2
  attn_resolutions: [ ]
  dropout: 0.0
  embed_dim: 3
  n_embed: 8192
  beta: 0.25

# DiT 配置 (保留)
Dit:
  hidden_size: 1152
  depth: 28
  num_heads: 16
  mlp_ratio: 4.0
  learn_sigma: False

# Diffusion 配置 (保留)
diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  num_diffusion_timesteps: 1000

# 优化器配置
optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  amsgrad: False
  eps: 0.00000001

# 训练参数
train:
  is_train: true
  seed: 61
  device_ids: [0]
  num_epochs: 50 
  sample_frames: 16 
  
  save_pic: "./out_pic/"
  save_ckp: "./ckp/head_binary/"
  
  optimizer:
    base_lr: 1e-3
    weight_decay: 0.05
    layer_decay: 0.8
